#ifndef ZDOC_ERROR_INTERFACE_H
#define ZDOC_ERROR_INTERFACE_H

enum ZDoc_Error {
    ZDOC_UNSUPPORTED_LANGUAGE = 0x00,
    ZDOC_OK = 0x01,
    ZDOC_DEFAULT = 0x02,
    ZDOC_PATH_TOO_LONG = 0x03,
    ZDOC_PARSER_FAILED = 0x04,
    ZDOC_OUT_OF_MEMORY = 0x05,
    ZDOC_FS_WALK_FAILED = 0x06,
    ZDOC_FILE_COUNT_UNAVAILABLE = 0x07,
    ZDOC_THREAD_CREATE_FAILED = 0x08,
    ZDOC_THREAD_WAIT_FAILED = 0x09
};

#endif